version: '3.9'
services:

  backend:
    container_name: backend
    image: zagrajzemna-backend
    build: .
    restart: always
    ports:
      - 4001:4000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    depends_on:
      - db
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    
  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4
  

volumes:
  pgdata:

networks:
 mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16