version: '3.9'
services:

  backend:
    container_name: backend
    image: zagrajzemna-backend
    build: .
    restart: always
    ports:
      - 4001:4000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    depends_on:
      - db
<<<<<<< Updated upstream
    volumes:
      - ./uploads:/app/uploads

=======
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    volumes:
      - ./uploads:/app/uploads
    
>>>>>>> Stashed changes
  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
<<<<<<< Updated upstream
=======
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3
    
>>>>>>> Stashed changes

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  pgdata:
  uploads:
